#include "uselessd10.h"

int bla = 30;

int uselessd_init10(int x) { bla += x; return uselessd_init11(x); }
int uselessd_init11(int x) { return uselessd_init12(x); }
int uselessd_init12(int x) { return uselessd_init13(x); }
int uselessd_init13(int x) { return uselessd_init14(x); }
int uselessd_init14(int x) { return uselessd_init15(x); }
int uselessd_init15(int x) { return uselessd_init16(x); }
int uselessd_init16(int x) { return uselessd_init17(x); }
int uselessd_init17(int x) { return uselessd_init18(x); }
int uselessd_init18(int x) { return uselessd_init19(x); }
int uselessd_init19(int x) { return uselessd_init20(x); }
int uselessd_init20(int x) { return uselessd_init21(x); }
int uselessd_init21(int x) { return uselessd_init22(x); }
int uselessd_init22(int x) { return uselessd_init23(x); }
int uselessd_init23(int x) { return uselessd_init24(x); }
int uselessd_init24(int x) { return uselessd_init25(x); }
int uselessd_init25(int x) { return uselessd_init26(x); }
int uselessd_init26(int x) { return uselessd_init27(x); }
int uselessd_init27(int x) { return uselessd_init28(x); }
int uselessd_init28(int x) { return uselessd_init29(x); }
int uselessd_init29(int x) { return uselessd_init30(x); }
int uselessd_init30(int x) { return uselessd_init31(x); }
int uselessd_init31(int x) { return uselessd_init32(x); }
int uselessd_init32(int x) { return uselessd_init33(x); }
int uselessd_init33(int x) { return uselessd_init34(x); }
int uselessd_init34(int x) { return uselessd_init35(x); }
int uselessd_init35(int x) { return uselessd_init36(x); }
int uselessd_init36(int x) { return uselessd_init37(x); }
int uselessd_init37(int x) { return uselessd_init38(x); }
int uselessd_init38(int x) { return uselessd_init39(x); }
int uselessd_init39(int x) { return uselessd_init40(x); }
int uselessd_init40(int x) { return uselessd_init41(x); }
int uselessd_init41(int x) { return uselessd_init42(x); }
int uselessd_init42(int x) { return uselessd_init43(x); }
int uselessd_init43(int x) { return uselessd_init44(x); }
int uselessd_init44(int x) { return uselessd_init45(x); }
int uselessd_init45(int x) { return uselessd_init46(x); }
int uselessd_init46(int x) { return uselessd_init47(x); }
int uselessd_init47(int x) { return uselessd_init48(x); }
int uselessd_init48(int x) { return uselessd_init49(x); }
int uselessd_init49(int x) { return uselessd_init50(x); }
int uselessd_init50(int x) { return uselessd_init51(x); }
int uselessd_init51(int x) { return uselessd_init52(x); }
int uselessd_init52(int x) { return uselessd_init53(x); }
int uselessd_init53(int x) { return uselessd_init54(x); }
int uselessd_init54(int x) { return uselessd_init55(x); }
int uselessd_init55(int x) { return uselessd_init56(x); }
int uselessd_init56(int x) { return uselessd_init57(x); }
int uselessd_init57(int x) { return uselessd_init58(x); }
int uselessd_init58(int x) { return uselessd_init59(x); }
int uselessd_init59(int x) { return uselessd_init60(x); }
int uselessd_init60(int x) { return uselessd_init61(x); }
int uselessd_init61(int x) { return uselessd_init62(x); }
int uselessd_init62(int x) { return uselessd_init63(x); }
int uselessd_init63(int x) { return uselessd_init64(x); }
int uselessd_init64(int x) { return uselessd_init65(x); }
int uselessd_init65(int x) { return uselessd_init66(x); }
int uselessd_init66(int x) { return uselessd_init67(x); }
int uselessd_init67(int x) { return uselessd_init68(x); }
int uselessd_init68(int x) { return uselessd_init69(x); }
int uselessd_init69(int x) { return uselessd_init70(x); }
int uselessd_init70(int x) { return uselessd_init71(x); }
int uselessd_init71(int x) { return uselessd_init72(x); }
int uselessd_init72(int x) { return uselessd_init73(x); }
int uselessd_init73(int x) { return uselessd_init74(x); }
int uselessd_init74(int x) { return uselessd_init75(x); }
int uselessd_init75(int x) { return uselessd_init76(x); }
int uselessd_init76(int x) { return uselessd_init77(x); }
int uselessd_init77(int x) { return uselessd_init78(x); }
int uselessd_init78(int x) { return uselessd_init79(x); }
int uselessd_init79(int x) { return uselessd_init80(x); }
int uselessd_init80(int x) { return uselessd_init81(x); }
int uselessd_init81(int x) { return uselessd_init82(x); }
int uselessd_init82(int x) { return uselessd_init83(x); }
int uselessd_init83(int x) { return uselessd_init84(x); }
int uselessd_init84(int x) { return uselessd_init85(x); }
int uselessd_init85(int x) { return uselessd_init86(x); }
int uselessd_init86(int x) { return uselessd_init87(x); }
int uselessd_init87(int x) { return uselessd_init88(x); }
int uselessd_init88(int x) { return uselessd_init89(x); }
int uselessd_init89(int x) { return uselessd_init90(x); }
int uselessd_init90(int x) { return uselessd_init91(x); }
int uselessd_init91(int x) { return uselessd_init92(x); }
int uselessd_init92(int x) { return uselessd_init93(x); }
int uselessd_init93(int x) { return uselessd_init94(x); }
int uselessd_init94(int x) { return uselessd_init95(x); }
int uselessd_init95(int x) { return uselessd_init96(x); }
int uselessd_init96(int x) { return uselessd_init97(x); }
int uselessd_init97(int x) { return uselessd_init98(x); }
int uselessd_init98(int x) { return uselessd_init99(x); }
int uselessd_init99(int x) { return uselessd_init100(x); }
int uselessd_init100(int x) { return uselessd_init101(x); }
int uselessd_init101(int x) { return uselessd_init102(x); }
int uselessd_init102(int x) { return uselessd_init103(x); }
int uselessd_init103(int x) { return uselessd_init104(x); }
int uselessd_init104(int x) { return uselessd_init105(x); }
int uselessd_init105(int x) { return uselessd_init106(x); }
int uselessd_init106(int x) { return uselessd_init107(x); }
int uselessd_init107(int x) { return uselessd_init108(x); }
int uselessd_init108(int x) { return uselessd_init109(x); }
int uselessd_init109(int x) { return uselessd_init110(x); }
int uselessd_init110(int x) { return uselessd_init111(x); }
int uselessd_init111(int x) { return uselessd_init112(x); }
int uselessd_init112(int x) { return uselessd_init113(x); }
int uselessd_init113(int x) { return uselessd_init114(x); }
int uselessd_init114(int x) { return uselessd_init115(x); }
int uselessd_init115(int x) { return uselessd_init116(x); }
int uselessd_init116(int x) { return uselessd_init117(x); }
int uselessd_init117(int x) { return uselessd_init118(x); }
int uselessd_init118(int x) { return uselessd_init119(x); }
int uselessd_init119(int x) { return uselessd_init120(x); }
int uselessd_init120(int x) { return uselessd_init121(x); }
int uselessd_init121(int x) { return uselessd_init122(x); }
int uselessd_init122(int x) { return uselessd_init123(x); }
int uselessd_init123(int x) { return uselessd_init124(x); }
int uselessd_init124(int x) { return uselessd_init125(x); }
int uselessd_init125(int x) { return uselessd_init126(x); }
int uselessd_init126(int x) { return uselessd_init127(x); }
int uselessd_init127(int x) { return uselessd_init128(x); }
int uselessd_init128(int x) { return uselessd_init129(x); }
int uselessd_init129(int x) { return uselessd_init130(x); }
int uselessd_init130(int x) { return uselessd_init131(x); }
int uselessd_init131(int x) { return uselessd_init132(x); }
int uselessd_init132(int x) { return uselessd_init133(x); }
int uselessd_init133(int x) { return uselessd_init134(x); }
int uselessd_init134(int x) { return uselessd_init135(x); }
int uselessd_init135(int x) { return uselessd_init136(x); }
int uselessd_init136(int x) { return uselessd_init137(x); }
int uselessd_init137(int x) { return uselessd_init138(x); }
int uselessd_init138(int x) { return uselessd_init139(x); }
int uselessd_init139(int x) { return uselessd_init140(x); }
int uselessd_init140(int x) { return uselessd_init141(x); }
int uselessd_init141(int x) { return uselessd_init142(x); }
int uselessd_init142(int x) { return uselessd_init143(x); }
int uselessd_init143(int x) { return uselessd_init144(x); }
int uselessd_init144(int x) { return uselessd_init145(x); }
int uselessd_init145(int x) { return uselessd_init146(x); }
int uselessd_init146(int x) { return uselessd_init147(x); }
int uselessd_init147(int x) { return uselessd_init148(x); }
int uselessd_init148(int x) { return uselessd_init149(x); }
int uselessd_init149(int x) { return uselessd_init150(x); }
int uselessd_init150(int x) { return uselessd_init151(x); }
int uselessd_init151(int x) { return uselessd_init152(x); }
int uselessd_init152(int x) { return uselessd_init153(x); }
int uselessd_init153(int x) { return uselessd_init154(x); }
int uselessd_init154(int x) { return uselessd_init155(x); }
int uselessd_init155(int x) { return uselessd_init156(x); }
int uselessd_init156(int x) { return uselessd_init157(x); }
int uselessd_init157(int x) { return uselessd_init158(x); }
int uselessd_init158(int x) { return uselessd_init159(x); }
int uselessd_init159(int x) { return uselessd_init160(x); }
int uselessd_init160(int x) { return uselessd_init161(x); }
int uselessd_init161(int x) { return uselessd_init162(x); }
int uselessd_init162(int x) { return uselessd_init163(x); }
int uselessd_init163(int x) { return uselessd_init164(x); }
int uselessd_init164(int x) { return uselessd_init165(x); }
int uselessd_init165(int x) { return uselessd_init166(x); }
int uselessd_init166(int x) { return uselessd_init167(x); }
int uselessd_init167(int x) { return uselessd_init168(x); }
int uselessd_init168(int x) { return uselessd_init169(x); }
int uselessd_init169(int x) { return uselessd_init170(x); }
int uselessd_init170(int x) { return uselessd_init171(x); }
int uselessd_init171(int x) { return uselessd_init172(x); }
int uselessd_init172(int x) { return uselessd_init173(x); }
int uselessd_init173(int x) { return uselessd_init174(x); }
int uselessd_init174(int x) { return uselessd_init175(x); }
int uselessd_init175(int x) { return uselessd_init176(x); }
int uselessd_init176(int x) { return uselessd_init177(x); }
int uselessd_init177(int x) { return uselessd_init178(x); }
int uselessd_init178(int x) { return uselessd_init179(x); }
int uselessd_init179(int x) { return uselessd_init180(x); }
int uselessd_init180(int x) { return uselessd_init181(x); }
int uselessd_init181(int x) { return uselessd_init182(x); }
int uselessd_init182(int x) { return uselessd_init183(x); }
int uselessd_init183(int x) { return uselessd_init184(x); }
int uselessd_init184(int x) { return uselessd_init185(x); }
int uselessd_init185(int x) { return uselessd_init186(x); }
int uselessd_init186(int x) { return uselessd_init187(x); }
int uselessd_init187(int x) { return uselessd_init188(x); }
int uselessd_init188(int x) { return uselessd_init189(x); }
int uselessd_init189(int x) { return uselessd_init190(x); }
int uselessd_init190(int x) { return uselessd_init191(x); }
int uselessd_init191(int x) { return uselessd_init192(x); }
int uselessd_init192(int x) { return uselessd_init193(x); }
int uselessd_init193(int x) { return uselessd_init194(x); }
int uselessd_init194(int x) { return uselessd_init195(x); }
int uselessd_init195(int x) { return uselessd_init196(x); }
int uselessd_init196(int x) { return uselessd_init197(x); }
int uselessd_init197(int x) { return uselessd_init198(x); }
int uselessd_init198(int x) { return uselessd_init199(x); }
int uselessd_init199(int x) { return uselessd_init200(x); }
int uselessd_init200(int x) { return x * x/30; }
