#!/usr/bin/perl -w
use strict;
use warnings;
use v5.14;
use POSIX qw(ceil floor);

die "usage : ./cdf.pl [<file>]" if @ARGV > 1;

my ($tempx, %freq,  @inp);
my $num_tot = 0;
sub by_number { $a <=> $b }

while (<>) {
    @inp = split /\s+/;

    $tempx = $inp[0];
    chomp($tempx);

    $freq{$tempx} ++;
    $num_tot++;
}

$tempx = 0;

for (sort by_number keys %freq) {
    if (defined($_)) {
        say $_, ' ', $freq{$_}/$num_tot;
    }
}

#for (sort by_number keys %freq) {
#    if (defined($_)) {
#        $tempx += $freq{$_};
#        ;
#        say $_, ' ', $tempx/$num_tot;
#    }
#}


=head1 NAME

cdf - to generate CDF files used latter to generate the graphs.

=head1 SYNOPSIS

    ./cdf.pl owd-file

=head1 DESCRIPTION

cdf.pl is a tool to generate cdf files from a file generated with
F<logparse>. It will print the results in two files:
owd-file.cdf.absolute and owd-file.cdf.relative.

=head1 PARAMETERS

=over 1

=item B<owd-file>

The owd-file is generated with the F<logparse> program.

=back

=head1 SEE-ALSO

This program uses F<autoscale-cdf.pl>, F<cdf.pl>,
F<graph_absolute_day.sh>, F<launcher>.

=cut
